apiVersion: batch/v1
kind: CronJob
metadata:
  name: hasher-cronjob
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hasher
            image: hasher:1.0
            envFrom:
            - configMapRef:
                name: hasher-config
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            hostPath:
              path: /mnt/c/Users/taljo/PycharmProjects/pythonProject/example
